openapi: 3.0.3
info:
  title: Traits Microservice API
  version: 1.3.0
  description: |
    API системы трейтов лидеров. 
    **Архитектурное решение:** 
    1. Первичным идентификатором является `leader_uuid`.
    2. Для обратной совместимости с iOS v2.4 в ответе передается `legacy_leader_id`. 
    3. Использование `legacy_leader_id` в качестве ключа в новых запросах запрещено.
servers:
  - url: https://api.cliometrics.internal/v1
    description: Production server

paths:
  /traits/{leader_uuid}:
    get:
      summary: Получить активные трейты лидера
      operationId: getLeaderTraits
      tags:
        - Traits
      parameters:
        - name: leader_uuid
          in: path
          required: true
          description: Уникальный идентификатор лидера (UUID)
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: current_date
          in: query
          required: false
          description: Текущая игровая дата (ГГГГ-ММ-ДД) для обсчета сезонных эффектов (HoI4 style).
          schema:
            type: string
            format: date
            example: "1941-06-22"
      responses:
        '200':
          description: Успешный возврат данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaderTraitsResponse'
        '400':
          description: Ошибка валидации UUID или даты

  /traits/bulk:
    post:
      summary: Массовый запрос трейтов
      operationId: getBulkTraits
      tags:
        - Traits
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - leader_uuids
              properties:
                leader_uuids:
                  type: array
                  items:
                    type: string
                    format: uuid
                  example: ["550e8400-e29b-41d4-a716-446655440000", "671e8400-e29b-41d4-a716-446655440001"]
                current_date:
                  type: string
                  format: date
                  example: "1941-06-22"
      responses:
        '200':
          description: Словарь результатов, где ключи — UUID лидеров
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/LeaderTraitsResponse'

components:
  schemas:
    LeaderTraitsResponse:
      type: object
      description: Объект ответа с привязкой к идентификаторам
      properties:
        leader_uuid:
          type: string
          format: uuid
          description: Основной системный идентификатор
          example: "550e8400-e29b-41d4-a716-446655440000"
        legacy_leader_id:
          type: string
          description: "Костыль для маппинга с Legacy Core (iOS v2.4). НЕ ИСПОЛЬЗОВАТЬ как PK."
          example: "1046"
        traits:
          type: array
          items:
            $ref: '#/components/schemas/Trait'

    Trait:
      type: object
      required:
        - name
        - availability
      properties:
        name:
          type: string
          example: "Great Purge Survivor"
        description:
          type: string
          example: "Increases political stability but lowers army morale."
        icon_url:
          type: string
          format: uri
          description: Полный абсолютный URL к ассету на CDN.
          example: "https://cdn.internal/icons/icon_purge_skull.png"
        availability:
          type: object
          properties:
            is_active:
              type: boolean
              example: true
            reason:
              type: string
              description: Пояснение статуса активности (например, 'Active only in winter')
              example: "Active only between 1936-01-01 and 1939-12-31"
        effect_modifiers:
          type: object
          additionalProperties:
            type: number
          example:
            stability: 0.15
            army_org: -0.1
